version: 2
jobs:
  build:
    docker:
      - image: "miktex/miktex"
    steps:
      # Always try to restore packages from cache first
      - restore_cache:
          name: Restoring packages
          keys:
            - v2-packages-
      # Will update packages or otherwise just update the db so new packages can be installed at build
      - run:
          name: Update local packages
          command: mpm --update
      # Code is now required to restore auxfiles into
      - checkout
      # Always restore the most recent auxfile cache
      - restore_cache:
          name: Restoring auxfiles and outfiles
          keys:
            - v2-auxfiles-
      # TODO: Fix outdir being in srcdir
      - run: 
          name: Compile PDFs
          working_directory: src
          command: latexmk -pdfxe -outdir=out
      # Only create a new package cache if something changed
      # First test: sha256 everything. Probably very slow.
      - run:
          name: Hash package directory
          command: find /miktex/.miktex -type f -exec sha256sum {} \; > packageHashFile
      - save_cache:
          name: Saving packages 
          key: v2-packages-{{ checksum "packageHashFile" }}
          paths: 
            - /miktex/.miktex
      - run:
          name: Hash output folder  # To check for changes in entire folder
          command: find src/out -type f -exec sha256sum {} \; > outHashFile
      - save_cache:
          name: Saving auxfiles and outfiles
          key: v2-auxfiles-{{ checksum "outHashFile" }}
          paths:
            - src/out
      - deploy:
          name: Move PDFs to artifact folder
          command: |
            mkdir PDFs
            mv src/out/*.pdf $_ 
      - deploy:
          name: Move logs to log folder
          command: |
            mkdir logs
            mv src/out/*.log $_
          when: always
      - store_artifacts:
          path: PDFs
      - store_artifacts:
          path: logs