version: 2
jobs:
  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run: make
      - deploy: mv examples/*.pdf output
      - store_artifacts:
          path: output