version: 2
jobs:
  build:
    docker:
      - image: "raabf/latex-versions:texlive2018"
    steps:
      - checkout
      - run: 
          name: Compile PDFs
          working_directory: src
          command: latexmk -pdfxe
      - deploy:
          name: Move PDFs to output folder
          command: mkdir out; mv src/*.pdf $_ 
      - store_artifacts:
          path: out