version: 2
jobs:
  build:
    docker:
      - image: "miktex/miktex"
    steps:
      - checkout
      - run: 
          name: Compile PDFs
          working_directory: src
          command: latexmk -pdfxe -quiet
      - deploy:
          name: Move PDFs to output folder
          command: mkdir out; mv src/*.pdf $_ 
      - store_artifacts:
          path: out