version: 2
jobs:
  build:
    docker:
      - image: "miktex/miktex"
    steps:
      - restore_cache:
          name: Restoring packages
          keys:
            # - v2-packages-{{ checksum "src/externalpackages.sty" }}
            - v2-packages-
      - run:
          name: Update local packages (Dry run only)
          command: mpm --list | grep ^i
      - checkout
      - restore_cache:
          name: Restoring auxfiles and outfiles
          keys:
            - v2-auxfiles-
      - run: 
          name: Compile PDFs
          working_directory: src
          command: latexmk -pdfxe -outdir=out
      # - run:
      #     name: Hash package directory

      - save_cache:
          name: Saving packages 
          key: v2-packages-{{ checksum "src/externalpackages.sty" }}
          paths: 
            - /miktex/.miktex
      - run:
          name: Hash output folder  # To check for changes in entire folder
          command: find src/out -type f -exec md5sum {} \; | md5sum > outHashFile
      - save_cache:
          name: Saving auxfiles and outfiles
          key: v2-auxfiles-{{ checksum "outHashFile" }}
          paths:
            - src/out
      - deploy:
          name: Move PDFs to artifact folder
          command: |
            mkdir PDFs
            mv src/out/*.pdf $_ 
      - deploy:
          name: Move logs to log folder
          command: |
            mkdir logs
            mv src/out/*.log $_
          when: always
      - store_artifacts:
          path: PDFs
      - store_artifacts:
          path: logs